### PR TITLE
Update to 4.5.0 fix #2 fix #5

### LINKED ISSUE #2: Needs a screenshot or two in the appdata
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

### LINKED ISSUE #5: Update to release 4.5.0

### PR DESCRIPTION
**Pull request by nedrichards**

### CODE REVIEW

**Comment by nedrichards** [comment]
bot, build

**Comment by nedrichards** [comment]
Hrm, this doesn't actually show an app for me. I get a spinner and then blank, which is normally a connectivity issue.
Also:
`error: ################### !! Update server down !! ##################
`
On the command line.

**Comment by TingPing** [comment]
Everything ran perfectly here, maybe it was a temporary network issue?

**Comment by nedrichards** [comment]
Yeah - I'm having some network issues - glad it works. Will hit the merge button.

**Pull request merged**
